#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 8

#define VERSION_STRING "0.0.1"
#define VERSION_FULL_STRING "0.0.1-build8"

#define BUILD_DATE "2025-07-09"
#define BUILD_TIME "21:49:48"
#define BUILD_TIMESTAMP "20250709214948"

#define VERSION_INFO_STRING "v0.0.1 (8) built on 2025-07-09 21:49:48"

#endif // VERSION_H
