#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 20

#define VERSION_STRING "0.0.1"
#define VERSION_FULL_STRING "0.0.1-build20"

#define BUILD_DATE "2025-07-13"
#define BUILD_TIME "22:00:41"
#define BUILD_TIMESTAMP "20250713220041"

#define VERSION_INFO_STRING "v0.0.1 (20) built on 2025-07-13 22:00:41"

#endif // VERSION_H
